### ISSUE TITLE
[Bug] skip_gram_sample assert rank is 1

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#12]
While converting the tests for skip_gram_ops, I noticed a test that was failing in TF2 eager execution, but I'm not sure why.

This [test](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/python/skip_gram_ops_test.py#L244):
```
with self.assertRaises(ValueError):
    invalid_tensor = constant_op.constant([[b"the"], [b"quick"], [b"brown"]])
    text.skip_gram_sample(invalid_tensor)
```

Should raise an error because of [this check in the op definition](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/cc/ops/skip_gram_ops.cc#L37). When decorating with `@test_util.run_deprecated_v1` the test correctly passes (error is raised), but otherwise it fails to raise an Error. 

Is this related to inspecting the rank of EagerTensors? Or is something else at play?

**Comment by karmel** [comment]
@jaingaurav - Is this something you have seen? Can you take a look? (Note that this is for the Addons repo, which is migrating functionality currently in contrib.)

**Comment by jaingaurav** [comment]
`@test_util.run_deprecated_v1` will cause the test to run in graph mode hence the check fires during graph construction. In Eager, you should see a [slightly different assertion](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/text/kernels/skip_gram_kernels.cc#L50) pop up due to a runtime check. This results in an `InvalidArgumentError` exception. The test need to be modified to handle both types of assertions. One approach would be to use something like `self.assertRaisesRegexp(Exception, <some string that matches both exceptions>)`

**Comment by seanpmorgan** [comment]
@jaingaurav Thank you very much for looking into this. So if I remove [this comment and the assertion context](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/text/python/skip_gram_ops_test.py#L271)  then I still see the test as passing and no Error at all being raised.

Seems like I would need to add a new OP_REQUIRES in the Compute method that verifies tensor rank?

**Comment by jaingaurav** [comment]
@seanpmorgan: Yes, that would be advisable to ensure better safety in eager mode.

**Comment by facaiy** [comment]
@jaingaurav So, will shape inference be supported for eager mode later? Otherwise, duplicate codes exist in both graph constructing and kernel computing.
