### ISSUE TITLE
Support Python 3.8 (as does TF 2.2)

### ISSUE THREAD

**Issue by bersbersbers** [tensorflow/addons#1376]
**Describe the bug**

Since TensorFlow 2.2 will support Python 3.8 (https://github.com/tensorflow/tensorflow/issues/33374#issuecomment-599102810), I feel that `tensorflow_addons` should do the same, especially in the light of https://github.com/tensorflow/addons/issues/1320.

**Comment by gabrieldemarmiesse** [comment]
Our codebase is already compatible with python 3.8. So we don't need to do anything (if you take https://github.com/tensorflow/addons/blob/master/tools/docker/cpu_tests.Dockerfile and change the python version to 3.8, you'll see the tests are passing). Maybe what you're referring to is to have a wheel on pypi that supports python 3.8. We'll do that once we release the wheels on pypi with support to TF 2.2.0, currently we only target stable versions of tensorflow. Our release should be around the same time that TF2.2.0 is stable. So you can track #1320.

If you really really can't wait, and that you don't use custom cuda ops (compiled ops) of TF addons, you can install 
* python 3.8
* TF2.2.0rc1 
* `pip install git+https://github.com/tensorflow/addons.git`

and that should be enough.

If you want to use custom ops, you'll have to compile them yourself, you can use the https://github.com/tensorflow/addons/blob/master/CONTRIBUTING.md to get started. 

I'll be closing this issue since it's already on our roadmap. You can track the progress in #1320 , and maybe help you wish to :)

**Comment by bersbersbers** [comment]
Thanks, that was super helpful to get it up and running for testing.

**Comment by bersbersbers** [comment]
@gabrieldemarmiesse #130 was closed on March 27:
> We're now compatible with TF 2.2.

And while `tfa-nightly` has PyPI packages for 3.8 (https://pypi.org/project/tfa-nightly/#files), `tensorflow-addons` still doesn't despite an April 10 release (https://pypi.org/project/tensorflow-addons/#files). What else should I track to follow stable Python 3.8 support via PyPI?

**Comment by gabrieldemarmiesse** [comment]
We plan for a new release tomorrow :)

**Comment by seanpmorgan** [comment]
@bersbersbers 0.10 has been published with python3.8 wheels available.
