### ISSUE TITLE
Global ignore pylint not-callable

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#151]
We've had several issues with pylint throwing object not callable errors. I suspect that this is all due to the tf export paradigm described in this thread:
https://groups.google.com/a/tensorflow.org/forum/#!topic/addons/-QEXKmznCdA

I believe pylint is unable to follow the inheritance on the public API and it will fail because of that. I worry that contributors will get discouraged with the style failures even though the code is correct.

Thoughts on adding `not-callable` as a global ignore? I'm not sure how often that lint error would catch something that wouldn't fail in a test.

**Comment by kyleabeauchamp** [comment]
Seems reasonable to me as a temporary bandaid.  I think streamlining the review process is worthwhile so that new contributors can better separate signal from noise.

**Comment by armando-fandango** [comment]
Totally agree @seanpmorgan  Better to add global ignore in our make/build/pylint config instead of adding `#disable: non-callable`.in the code everywhere. That way some day when pylint starts working with tf public API exports, we can remove the global ignore easily, but searching and removing from all of our code files would a bit of work.

**Comment by facaiy** [comment]
Yeah, agree, and I create a PR to fix it.
