### ISSUE TITLE
ABI settings in BUILD files causing issues

### ISSUE THREAD

**Issue by mfojtak** [tensorflow/addons#174]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution: Ubuntu 18.04 
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly-2.0-preview==2.0.0.dev20190405
- TensorFlow Addons installed from (source, PyPi): source
- TensorFlow Addons version: latest
- Python version and type (eg. Anaconda Python, Stock Python as in Mac, or homebrew installed Python etc): 3.7
- Bazel version (if compiling from source): 0.24.1
- GCC/Compiler version (if compiling from source): 7.3.0
- Is GPU used? (yes/no): yes
- GPU model (if used): Tesla P100

**Describe the bug**

When running an app using addons build from source, it crashes with undefined symbol error.
```
undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv
```
There are BUILD files under /tensorflow_addons/custom_ops
When I remove *-D_GLIBCXX_USE_CXX11_ABI=0* from these files, it starts working again.

Why are these lines present in the BUILD files?
Should I raise PR and get them removed?

**Comment by seanpmorgan** [comment]
Hi Michal,

Thanks for bringing this up. So the build process is a bit hacky while we wait for a build toolchain which is manylinux2010 compatible (Should be by the end of the month). Since TF is compiled with gcc 4.8 we need these ABI flags to maintain compatibility in case addons is compiled with gcc>=5. As described:
https://github.com/calid/docs/blob/master/site/en/extend/adding_an_op.md#build-the-op-library

I noticed you're running python3.7 which is a broken whl as far as I know (they had to use ubuntu16 so it's unlike all of the other TF whls). Could you try this again using the py36 or any other version?

If you really want to run py37 then dropping the ABI flags as you have done and compiling from source should be the fix. Let me know if neither of these options is suitable for you. In either case this should all be cleaned up in the coming weeks.

**Comment by seanpmorgan** [comment]
Some more info:
https://github.com/tensorflow/tensorflow/issues/27067

**Comment by kyleabeauchamp** [comment]
FYI I've been able to (~2 weeks ago, around the time of my last commit) use py37 (conda-forge miniconda) by flipping the CXX11_ABI flag in all relevant places in the bazel files.

**Comment by kyleabeauchamp** [comment]
It would also be great for us to make sure that the build chain plays nicely with miniconda/conda-forge python versions.  Even if don't want to officially support the conda-forge packages (which I've helped out with a bit in my spare time), however, I think we do want to make sure that users with a conda-forge/miniconda environment can easily build from source when necessary.

**Comment by seanpmorgan** [comment]
Certainly agree. I would like to revisit the issue you saw once we've finalized the build toolchain.

FWIW pip packaging is really not ideal, and conda is a much preferable way to install performant packages. @kyleabeauchamp would you be interested in helping us setup our conda-forge package? Probably will wait until we've finalized our build process but it's certainly on our TODO.

**Comment by kyleabeauchamp** [comment]
Yep, if there's interest I can start opening PRs for the TF 2.0 packages.

**Comment by kyleabeauchamp** [comment]
It will take some work getting the pre-requisites built.  The DAG for TF and tensorboard are pretty confusing IMHO, with the split of estimator etc.

**Comment by seanpmorgan** [comment]
Closing this issue for now, but feel free to re-open if we don't get this solved in the coming weeks.

**Comment by kyleabeauchamp** [comment]
Will we need cuda to build add-ons?  That will be a license issue for conda
forge and Travis.
