### ISSUE TITLE
How to use CuDNN on Seq2Seq with attention.

### ISSUE THREAD

**Issue by dathudeptrai** [tensorflow/addons#1892]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): Binary 2.2.0
- TensorFlow-Addons version and how it was installed (source or binary): 0.9.1
- Python version: 3.7
- Is GPU used? (yes/no): yes

**Describe the bug**

Training speed slow with example seq2seq.

**Code to reproduce the issue**

https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt.

**Other info / logs**

As Tensorflow RNN tutorial (https://www.tensorflow.org/guide/keras/rnn), they said that cudnn only available with layer level rather than cell level. On Tensorflow official example nmt (https://www.tensorflow.org/tutorials/text/nmt_with_attention), they use GRU layer while tensorflow_addons example (https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt) use LSTMCell instead, so i think an example is not good. is there any way to use cudnn with tensorflow addons seq2seq attention, like tensorflow tutorial ?.

**Comment by guillaumekln** [comment]
cuDNN is fast because it can parallelize over multiple timesteps. However, the `AttentionWrapper` class needs to run the cell timestep by timestep to implement input feeding: the decoder output at time `t` is fed as input at time `t + 1` (also described in [Luong et al. 2015](https://www.aclweb.org/anthology/D15-1166/)). Because of this time dependency, there is little benefit in using cuDNN.

**Comment by dathudeptrai** [comment]
Got it, thanks for ur infomation.
