### ISSUE TITLE
Add pip upgrade to all tutorials

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#2124]
We haven't seen a fast enough turn around to depend on Colab keeping TFA up to date. See:
https://github.com/googlecolab/colabtools/issues/1243

As a result we've had a number of issues regarding incompatible version so it makes sense we just include `!pip install --upgrade tensorflow-addons` to all of our tutorials

**Comment by yashk2810** [comment]
All of TF addons notebooks are currently failing when publishing to tensorflow.org/addons because it doesn't have an addons install at the top. This is required regardless of what colab does.

So please update this as soon as possible since no updates to the docs are being pushed to the site as the notebooks keep failing.

**Comment by yashk2810** [comment]
List of failing notebooks: 

https://github.com/tensorflow/addons/blob/master/docs/tutorials/optimizers_lazyadam.ipynb
https://github.com/tensorflow/addons/blob/master/docs/tutorials/layers_weightnormalization.ipynb
https://github.com/tensorflow/addons/blob/master/docs/tutorials/tqdm_progress_bar.ipynb
https://github.com/tensorflow/addons/blob/master/docs/tutorials/losses_triplet.ipynb
https://github.com/tensorflow/addons/blob/master/docs/tutorials/layers_normalizations.ipynb

**Comment by yashk2810** [comment]
All the notebooks should also be runnable locally. Many users won't necessarily have TFA installed hence we need this in the notebooks itself. 

This is followed by all other subsites on tensorflow.org so TFA also needs to add `!pip install tensorflow-addons` to all its tutorials so that they can be published on tensorflow.org.
