### ISSUE TITLE
How about we stop deprecating everything every other release....

### ISSUE THREAD

**Issue by acidtonic** [tensorflow/addons#2170]
I can't believe how terrible the experience is using these tools.

It seems the whole process is playing jigsaw puzzle games trying to line up all the versions so that *something*, anything works.

* We are sorry but your original working tensorflow code for training is being moved to generic tf.slim for generic training.
* We are sorry but your changed code using generic tf.slim was not specific enough, make these changes.
* We are sorry but after having you do all this, tf.slim is moving to contrib.
* Okay, now contrib is going away and here is a basic script that will just tell you cannot change anything for you, code it all again yourself. All 3rd party guides are now worthless.

(Roughly after about a year of this, I realized what a waste of time and left tensorflow)

* Now I'm back only to try to get other frameworks (which work) models converted to tflite since it's the only decent solution for performance on mobile.
* Of course the tools to convert to tf-lite require a bunch of tensorflow things to be installed again.

Oops, I'm using Cuda 10.1, watch pip packages try opening libcudart-9. 
Install tensorflow 2.x from source for cuda 10.1, whoops it wants newer python now.
Install tensorflow addons, BOOM it doesn't support tensorflow 2.4.0.
Backdate to tensorflow 2.1, rebuild everything.
Install tensorflow addons, BOOM it doesn't support tensorflow <2.2.0.

I know this will just get closed and someone will mention that I'm wrong for being a Gentoo user who expects to build from source and not limp off of a packaging system to fix a project that cannot properly figure out how to handle backwards compatibility. Nor will I use some "docker" container....

Do you need some help coding? Is this intentional lock-in related movement to keep everyone rewriting things?  Can you stop deprecating things long enough for someone to actually build something longer than a year and have it work when they are done? Thanks.

**Comment by seanpmorgan** [comment]
Please take this type of complaint to the core TF repo (I suggest you re-word it to be more constructive though). This is a community maintained repo and we do not make decisions on just about all of the complaints you raised. 

FWIW There is no released TF 2.4, and TF-Addons has a compatible version for all TF 2.x pip packages:
https://github.com/tensorflow/addons#python-op-compatility

We do support building from source and to answer your question, we would love some "help coding". That's why its an open source community repo.

**Comment by acidtonic** [comment]
This comment is deprecated, please rewrite in the manner desired and post to the main topic

;)

**Comment by bhack** [comment]
@acidtonic Partially I can understand your frustration and maybe you speaks in a "passionate mood" also because you have invested a lot of time/projects relying on the TF library/ecosystem.
But honestly this in not in the perimeter of Tensorflow Addons cause this SIG repository is maintained only by volunteers on their spare time. 
As you probably know in the opensource volunteers perimeter projects you have just two solutions: you can just switch on concurrent tools, or you can invest your time to try to change what you suppose it is wrong investing your time directly in the project.
I think that some of your topics are better to be exposed in the most pertinent community forums. You can find the list here:
https://www.tensorflow.org/community/forums

Probably a Tensorflow's technical manager will reply to you on these channels.

P.s. TF as many other opensource projects/communities adopt the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/) So if you are going to write on these channels please try to expose you motivations in a way that it is not in contrast with the community policy.

**Comment by acidtonic** [comment]
I logged an issue on the main tensorflow site. I'm sure they will bounce me around to log it somewhere else eventually.
