### ISSUE TITLE
Need to better understand Boilerplate Code.

### ISSUE THREAD

**Issue by angadsinghsandhu** [tensorflow/addons#2220]
Hey Everyone,

I have been trying to deep-dive into the source code of various `optimizers` .

Quite often I find some methods that I'm having a hard time to understand. (For Example : `_create_slots`, `_resource_apply_dense`, `_prepare_local`,).

Could someone please point me toward where I should look to understand these better? I have also tried looking inside `tf.keras.optimizers.Optimizer` but I was having a hard time.

thanks a lot in advance 😊.

**Comment by seanpmorgan** [comment]
Hi @angadsinghsandhu ! I've found this blog to be helpful:
https://cloudxlab.com/blog/writing-custom-optimizer-in-tensorflow-and-keras/

Also the internal doc strings for keras optimizers have great explanations that are rendered on the website:
https://keras.io/api/optimizers/#core-optimizer-api

Closing this since it isn't quite an Addons issue. If there are further questions I would suggest the Keras Google Group.
