### ISSUE TITLE
Problems about SpectralNormalization

### ISSUE THREAD

**Issue by RayGuo-C** [tensorflow/addons#2534]
Dear,

When I use ```tfa.layers.SpectralNormalization``` in discriminator network by training the DCGAN. But it shows following warning:
```
WARNING:tensorflow:5 out of the last 5 calls to <function SpectralNormalization.normalize_weights at 0x000001C14F9664C0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function SpectralNormalization.normalize_weights at 0x000001C1367A5B80> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
```

Looking forward to your reply.

Best Regards

**Comment by MegaCreater** [comment]
look #2575. Same problem here (with me) also. 
It due to repeated call of @tf.function in [Line - 106](https://github.com/tensorflow/addons/blob/v0.14.0/tensorflow_addons/layers/spectral_normalization.py#L106) of `tfa.layers.SpectralNormalization`.
If we make own api by just copy and pasting source code of  tfa.layers.SpectralNormalization (form [here](https://github.com/tensorflow/addons/blob/v0.14.0/tensorflow_addons/layers/spectral_normalization.py), as it is only of 130 Lines long, single py file) and remove @tf.function decorator it will not show this warning. This may work but does it effect performance or not I don't know.

**Comment by bhack** [comment]
Please try to benchmark with and without the `tf.function` (https://github.com/tensorflow/addons/issues/2575#issuecomment-927434490).

In the case you will not see too much performances penalties please open a PR to remove it.
