### ISSUE TITLE
Request for example: Focal Loss

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/addons#361]
It would be nice to have an example for how to use focal loss in an object detection pipeline.

Resources:
https://arxiv.org/pdf/1708.02002.pdf

**Comment by SSaishruthi** [comment]
Would like to work on this

**Comment by AakashKumarNain** [comment]
Not exactly object detection but as this one is a binary classification problem, so the same concept applies here. Check this out: https://www.kaggle.com/aakashnain/diving-deep-into-focal-loss

**Comment by SSaishruthi** [comment]
Thanks @AakashKumarNain

**Comment by AakashKumarNain** [comment]
You are welcome @SSaishruthi . I wanted to add an example when I submitted the `PR` for focal loss but for putting object detection as an example with focal loss requires a little verbose example with many moving parts, so I parked it for later at that point in time

**Comment by SSaishruthi** [comment]
I have a placeholder example PR for this. Will keep experimenting with different use cases. Thanks for the input

**Comment by bhack** [comment]
@seanpmorgan It could be also nice f the Tensorflow google team will start to contribute a little bit in Tensorflow addons repo instead of accumulate single person/small team code snippets in the new just announced Model Garden or in the Google research repos. 
See i.e. https://github.com/tensorflow/models/blob/master/official/vision/detection/modeling/losses.py#L25.
I don't know if we could open a general issue about this topic cause I've mentioned the same things on other tickets.
