### ISSUE TITLE
Import failed when using tensorflow version built from source

### ISSUE THREAD

**Issue by npuichigo** [tensorflow/addons#574]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow version and how it was installed (source or binary): 2.0.0 (build from source)
- TensorFlow-Addons version and how it was installed (source or binary): 0.6.0
- Python version: 3.6.8
- Is GPU used? (yes/no): yes

**Describe the bug**

When I install tensorflow from source code, addons cannot be imported successfully.

```shell
NotFoundError: tensorflow_addons/custom_ops/activations/_activation_ops.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

**Comment by seanpmorgan** [comment]
Hi @npuichigo thanks for creating this. I have recently noticed this issue and was going to investigate a little more before posting.

This generally occurs from a mismatch in what compiler version was used between TF and TFA. However, it looks like you built TF from source as well. I'll post any findings in this thread as we work through this.

**Comment by seanpmorgan** [comment]
So I plan on continuing looking into this (we should be able to match tfa and tf if both are built on the same machine), but wanted to provide a little more information.

The undefined symbol error occurs because of a mismatch in compilers that causes different symbol name managling. This general issue should be solved by this RFC that is already underway:
https://github.com/tensorflow/community/blob/1c87177cb21ad9e8e48a883b162ff0bedd6da42a/rfcs/20190814-kernel-and-op-registration.md

**Comment by seanpmorgan** [comment]
Consolidating in https://github.com/tensorflow/addons/issues/987
