### ISSUE TITLE
Feature request : Add more Scipy Optimizer

### ISSUE THREAD

**Issue by nicaogr** [tensorflow/addons#630]
Hi,

Could it be possible to wrap the [scipy.optimize.basinhopping](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.optimize.basinhopping.html) and [scipy.optimize.anneal](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.anneal.html) the same way the [tf.contrib.opt.ScipyOptimizerInterface](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/contrib/opt/python/training/external_optimizer.py) allow us to use method as LBFGS with Tensorflow to minimize a function ?

Thanks

**Comment by seanpmorgan** [comment]
So we had originally planned on moving SciPy optimizers to TFA (#3) but decided against it as it's difficult for us to maintain and there was not a substantial request from the community. Seeing as this issue is quite old I'm going to close this issue pending community requests. 

Feel free to re-open if there is a substantial need for this and we can consider possible paths forward. These generally don't fit the Keras/TFA API so we would need to consider how this would fit.

**Comment by kyleabeauchamp** [comment]
There are some implementations of LBFGS in tensorflow probability that I have been able to use on TF2.0, so that's a good starting point for folks interested in that functionality.
