### ISSUE TITLE
Unpooling layer in tensorflow

### ISSUE THREAD

**Issue by ziky90** [tensorflow/addons#632]
It would be nice to have in TensorFlow also the unpooling layer as it is described in the paper on deconvolution networks: http://cvlab.postech.ac.kr/research/deconvnet/

I was googling a bit and I found that the added unpooling layer would be handful also for others:
http://stackoverflow.com/questions/36548736/tensorflow-unpooling

**Comment by seanpmorgan** [comment]
Thanks for transferring. This seems like a nice fit in addons, though it will need to be converted to fit the Keras Layer API and have appropriate test cases.

**Comment by NEGU93** [comment]
Here it is my implementation also posted [stackoverflow](https://stackoverflow.com/a/66694687/5931672). You should apply the max-pooling using [tf.nn.max_pool_with_argmax](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool_with_argmax) and then pass the `argmax` result of `tf.nn.max_pool_with_argmax`

```
def unpooling(inputs, output_shape, unpool_mat):
        """
        Performs unpooling, as explained in:
        https://www.oreilly.com/library/view/hands-on-convolutional-neural/9781789130331/6476c4d5-19f2-455f-8590-c6f99504b7a5.xhtml
        :param inputs: Input Tensor.
        :param output_shape: Desired output shape. For example, on 2D unpooling, this should be 4D (because of number of samples and channels).
        :param argmax: Result argmax from tf.nn.max_pool_with_argmax
            https://www.tensorflow.org/api_docs/python/tf/nn/max_pool_with_argmax
        """
        flat_output_shape = tf.cast(tf.reduce_prod(output_shape), tf.int64)

        updates = tf.reshape(inputs, [-1])
        indices = tf.expand_dims(tf.reshape(argmax, [-1]), axis=-1)

        ret = tf.scatter_nd(indices, updates, shape=[flat_output_shape])
        ret = tf.reshape(ret, output_shape)
        return ret
```

This has a small bug/feature that is that if argmax has a repeated value it will perform an addition instead of just putting the value once. Beware of this if stride is 1. I don't know, however, if this is desired or not. This feature was also present in @Twice22 [solution](https://github.com/tensorflow/addons/issues/632#issuecomment-482580850) as I based my implementation on his code.

**Comment by pedrogalher** [comment]
My question seems pretty basic considering the level of this conversation.
How did you get to these expresions to extract the values for "x" and "y"?:

- y = argmax // (output_shape[2] * output_shape[3])

- x = argmax % (output_shape[2] * output_shape[3]) // output_shape[3]

What's the maths behind them?

Thank you
Pedro
