### ISSUE TITLE
Crash caused by _beam_search_ops.so in tensorflow-addons 0.5.x

### ISSUE THREAD

**Issue by CuiYifeng** [tensorflow/addons#646]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS 7
- TensorFlow version and how it was installed (source or binary): source 2.0.0
- TensorFlow-Addons version and how it was installed (source or binary): binary 0.5.0 / 0.5.2
- Python version: 3.6
- Is GPU used? (yes/no): no

**Describe the bug**

A segmentation fault related to "_beam_search_ops.so" occurs when running MLPerf GNMT, where the tensorflow (master) is built with GCC 6.3.0 and default options.

Using tensorflow (master) and tensorflow-addons (r0.5) both built by the offical or both built by myself won't cause the crash. Furthermore, tensorflow r2.0 (source) + tensorflow-addons 0.5.0 / 0.5.2 (binary) works.

BTW, could you provide your building options and environment for tensorflow?

**Comment by guillaumekln** [comment]
Does MLPerf provide their own version of TensorFlow? It sounds like that they are using a different toolchain.

**Comment by Zantares** [comment]
> Does MLPerf provide their own version of TensorFlow? It sounds like that they are using a different toolchain.

MLPerf doesn't provide any TF because it's only benchmark for different Arch to test DL performance. Each Arch may not have a standard release TF so that we need to build  from source by ourselves. We wan to know whether Addons use specific GCC or cmd to build which may be incompatible.

**Comment by guillaumekln** [comment]
@seanpmorgan Could you provide more details here? Thanks.

**Comment by seanpmorgan** [comment]
Hi, 

Apologies this isn't more straight forward. So In order to mach ABI compatibility with TensorFlow (pip packaged) we build our package with devtoolset-7 in the tensorflow/custom-op-ubuntu16 docker container: 
```
root@d83542b82ed5:/addons# /dt7/usr/bin/gcc --version
gcc (GCC) 7.3.1 20180303
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Building TFA and TF from source with the same toolchain should work, though we currently have an issue out for our GPU toolchain which uses nvcc:
https://github.com/tensorflow/addons/issues/574


In the near future this ABI instability is planning to be fixed by Core TF using stable C bindings:
https://github.com/tensorflow/community/blob/1c87177cb21ad9e8e48a883b162ff0bedd6da42a/rfcs/20190814-kernel-and-op-registration.md

Let me know if there is any more information you'd like provided

**Comment by seanpmorgan** [comment]
Closing. Feel free to re-open if there are more things to discuss.
