### ISSUE TITLE
Lifted Struct Loss Error

### ISSUE THREAD

**Issue by sarim-zafar** [tensorflow/addons#699]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab (Linux)
- TensorFlow version and how it was installed (source or binary): binary 2.0
- TensorFlow-Addons version and how it was installed (source or binary): binary 0.6.0
- Python version: 3
- Is GPU used? (yes/no): Yes

**Describe the bug**
I get an assert shape error when I try to initialize the LiftedStructLoss obj

`assert lshape.shape == 1 AssertionError` is the error I get. However, it can easily be resolved by removing the assert line. I have one more question, why does it say that the vector should not be l2 normalized? while in the case of semihardtriplet loss it says that the vector should be l2 normalized
**Code to reproduce the issue**
`import tensorflow_addons as tfa`
`tfa.losses.LiftedStructLoss()`

**Comment by WindQAQ** [comment]
1. That is similar to https://github.com/tensorflow/addons/issues/295. I would submit a PR later.
2. I think it is ok to take normalized embedding as input for lifted struct loss as there is no addition normalization done in the [paper](https://arxiv.org/pdf/1511.06452.pdf); triplet loss used in facenet model states the embedding should be normalized in [Figure 2](https://arxiv.org/pdf/1503.03832.pdf).

However, in both implementation, we do not check whether the embedding should be l2 normalized explicitly so the documentation is only a note for user rather than a constraint. Please correct me if I make wrong inferences. Thanks for reporting the issue!

**Comment by sarim-zafar** [comment]
1. Yes it is same as the one referenced above
2. I tried experimenting with l2 normalization of relu , sigmoid activation, relu activation. After a couple thousand iterations, the normalized embedding's loss stagnates while the other two keep decreasing. So there is definitely something specific to the implementation. I tried going through the paper for lifted struct loss but they don't mention normalization anywhere.
3. As for the triplet loss i am fine with it and yes i know they add normalization there.
