### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by cramertj** [tensorflow/addons#713]
The last pip release was 0.6.0 on October 4th: https://github.com/tensorflow/addons/releases

Would it be possible to get a new release, in particular one that includes the fix to https://github.com/tensorflow/addons/issues/703?

**Comment by Squadrick** [comment]
cc @seanpmorgan who might better answer when the next release will be. 

We've removed the op that was causing the failure with nightly tensorflow in #710. Using the latest tfa-nightly and tf-nightly should work.

**Comment by cramertj** [comment]
> Using the latest tfa-nightly and tf-nightly should work.

It does, thanks! To clarify, I'm actually a developer on [Tensorflow Federated](https://github.com/tensorflow/federated), and we'd like to publish a new release. However, we have a dependency on Tensorflow Addons and don't want to change our published release to depend on a nightly version of tfa.

**Comment by seanpmorgan** [comment]
Hi @cramertj unfortunately we're unable to release a new version of TFA as we're now utilizing functionality from TF-Core that was unavailable in 2.0 (e.g. https://github.com/tensorflow/addons/pull/669):
https://colab.research.google.com/drive/1wZjKZISINcrEchnxx8cadwiv_M96hYib

As soon as we get a 2.1 release candidate we'll be publish a new TFA 0.7 and then increment minor versions as the full 2.1 release approaches.

Is there a particular feature that you're looking for since 0.6? #703 was just an issue for nightly building -- but if there was a specific feature you're missing we could cherry-pick it into a 0.6.1 release and push it this weekend.

**Comment by MadsAdrian** [comment]
If a cherry-picked 0.6.1 release is done, it would be nice if the fix for #675 is included!

**Comment by seanpmorgan** [comment]
Closing. See https://github.com/tensorflow/addons/issues/725.  We'll hopefully have the new release in the next few days.
