### ISSUE TITLE
Add addons to top-level modules

### ISSUE THREAD

**Issue by fsx950223** [tensorflow/addons#718]
**Describe the feature and the current behavior/state.**
Add addons to top-level modules just like estimator for convenient
**Relevant information**
- Are you willing to contribute it (yes/no):
- Are you willing to maintain it going forward? (yes/no):
- Is there a relevant academic paper? (if so, where):
- Is there already an implementation in another framework? (if so, where):
- Was it part of tf.contrib? (if so, where):

**Which API type would this fall under (layer, metric, optimizer, etc.)**
tensorflow.addons
**Who will benefit with this feature?**
addons users
**Any other info.**

**Comment by seanpmorgan** [comment]
Hi @fsx950223 could you further explain what you're requesting? Are you asking for Addons to be a dependency of TF-Core just as Estimator is? 

If so it is highly unlikely to ever be a dependency as there is a major push for modular tensorflow:
https://github.com/tensorflow/community/pull/77

**Comment by fsx950223** [comment]
> Hi @fsx950223 could you further explain what you're requesting? Are you asking for Addons to be a dependency of TF-Core just as Estimator is?
> 
> If so it is highly unlikely to ever be a dependency as there is a major push for modular tensorflow:
> [tensorflow/community#77](https://github.com/tensorflow/community/pull/77)

For example:
If I install tensorflow_addons, I could use addons by
``` python
import tensorflow as tf
image=tf.addons.image.rotate(image)
```
rather than
``` python
import tensorflow_addons as tfa
image=tf.addons.image.rotate(image)
```

**Comment by seanpmorgan** [comment]
Understood. While I agree this would be a nice change for the end-user; that strategy has created a bit of a tangled mess for packaging TF. See this new RFC:
https://github.com/tensorflow/community/pull/182

It creates a circular dependency because TFA depends on TF and TF depends on TFA. Going forward it looks as though every component of the TF ecosystem will be it's own import (see RFC)

Closing, but thanks for the suggestion and we're always looking for end-user improvements!
