### ISSUE TITLE
CI: output log of each test target

### ISSUE THREAD

**Issue by facaiy** [tensorflow/addons#78]
There seems only one target `tensorflow_addons/ubuntu/py2/presubmit` in the detail page, check out: 
https://source.cloud.google.com/results/invocations/bcda13af-4a13-41c6-a7db-76ff8e3ec504/targets/tensorflow_addons%2Fubuntu%2Fpy2%2Fpresubmit/log

@av8ramit
Could we give all the details for each test target, like tensorflow/tensorflow? That would be greatly helpful for review.

**Comment by av8ramit** [comment]
Hi @facaiy unfortunately for reasons decided unbeknownst to me, the way the system internally is set up is that you can only run predefined bazel targets if you want the targets to be split up. I think this is for security reasons. Since the script is modified a lot externally, I've made the internal invocation a simple shell script call. We're discussing on what the best way to move forward is.

**Comment by facaiy** [comment]
@av8ramit Thank you for the detailed reply, Amit. I start to understand why we have only one presubmit target here. It has been good enough for me. Thanks again, we wouldn't have gotten here without your work. Please update the issue when new information becomes available :-)

**Comment by av8ramit** [comment]
No problem @facaiy glad I was able to help!
