### ISSUE TITLE
SWA does not work with BatchNormalization

### ISSUE THREAD

**Issue by johnarevalo** [tensorflow/addons#816]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow version and how it was installed (source or binary): `pip3 install tf-nightly (2.1.0.dev20191227)`
- TensorFlow-Addons version and how it was installed (source or binary): `pip3 install tfa-nightly (0.7.0.dev20191219)`
- Python version: `3.7.6`
- Is GPU used? (yes/no): no

**Describe the bug**

`KeyError: 'sequential/batch_normalization/moving_mean_71'` is raised when invoking the [assign_average_vars](https://github.com/tensorflow/addons/blob/886853/tensorflow_addons/optimizers/stochastic_weight_averaging.py#L181) in a model with `BatchNormalization` layers
**Code to reproduce the issue**
```
import tensorflow as tf
from tensorflow_addons.optimizers.stochastic_weight_averaging import SWA

# DATA
train_data, test_data = tf.keras.datasets.boston_housing.load_data()
train_ds = tf.data.Dataset.from_tensor_slices(train_data).shuffle(404).batch(32)
test_ds = tf.data.Dataset.from_tensor_slices(test_data).batch(32)

# MODEL
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(64, activation='relu', use_bias=True))
model.add(tf.keras.layers.BatchNormalization())
model.add(tf.keras.layers.Dense(1))

# OPTIMIZER
opt = SWA(tf.keras.optimizers.SGD())
model.compile(optimizer=opt, loss='mean_squared_error')
model.fit(train_ds, epochs=20)

# AFTER FIT. KeyError is raised
opt.assign_average_vars(model.variables)

for x_train, _ in train_ds:
    model(tf.cast(x_train, tf.float32), training=True)

model.evaluate(train_ds)
model.evaluate(test_ds)
```
**Other info / logs**
As workaround, I am ignoring `moving_mean` and `moving_variance` non-trainable variables by changing [this](https://github.com/tensorflow/addons/blob/886853/tensorflow_addons/optimizers/stochastic_weight_averaging.py#L205-L206) line:
```
assign_op = tf.group(
            [var.assign(self.get_slot(var, 'average')) for var in var_list])
```
to:
```
assign_op = tf.group(
            [var.assign(self.get_slot(var, 'average')) for var in var_list if var.trainable])
```

**Comment by seanpmorgan** [comment]
Thanks for the report!
cc @shreyashpatodia code owner.

**Comment by shreyashpatodia** [comment]
Thanks for pointing this out @johnarevalo!

I think what is happening is that when `var_list` is passed to `_create_slots` it does not contain the `moving_mean` and `moving_variance` variables. Thus, the `KeyError`.

I think the optimal solution is to look at when `_create_slots` is called and replicating that logic in `assign_average_vars` for consistency.

Do you think this makes sense as a solution?

**Comment by Squadrick** [comment]
Hey, took a look at this for #760 

The problem is that keras only passes trainable variables (`var_list`) to any optimizer. So `moving_average` and `moving_variance` of BatchNorm is never passed to the opt, and therefore we don't consider them when calculating the averaged update. 

For now, @johnarevalo fix of checking when if the variable is trainable should work. But I'm not sure if that makes sense. The `moving_average` and `moving_variance` of each BatchNorm is calculated based on the original variables and not the moving average weights.

**Comment by shreyashpatodia** [comment]
Yep. I don't think the `moving_mean` and `moving_average` learned during training are relevant for the averaged weights.

I have a note in my implementation saying that the user should make one more pass through the data to correctly calculate batch norm statistics. This would mean resetting the `moving_mean` and `moving_variance` and then running a pass through the data to learn the `scale` and the `offset` per batch norm layer.

I didn't make this part of the optimizer because I don't think this sort of logic where we make a pass through the data should exist in an optimizer. @Squadrick do you think we should add an auxiliary function that can be used to make stuff work with batch norm?

**Comment by Squadrick** [comment]
That seems to be the way the authors do it. Source code for implementation [here](https://github.com/timgaripov/swa/blob/4a2ddfdb2692eda91f2ac41533b62027976c605b/utils.py#L107) for the batch norm update. I'll get started with adding this to #760. 

@shreyashpatodia Could you take a look once I've completed the update?

**Comment by shreyashpatodia** [comment]
Yeah sure!

**Comment by seanpmorgan** [comment]
Closed with https://github.com/tensorflow/addons/pull/760?

**Comment by shreyashpatodia** [comment]
Yep.
